"""NeuroOps Engineering Department agents."""
from __future__ import annotations

import hashlib
import re

from core import Task
from core.base_agent import BaseAgent


class CodeWriterAgent(BaseAgent):
    department = "engineering"
    description = "Writes code implementations from specifications."

    def think(self, task: Task) -> tuple[str, float]:
        self.log("Analyzing specification...")
        spec = task.description or task.title
        lines = [
            "```python",
            f"# Auto-generated stub for: {task.title}",
            f"# Requirement: {spec[:120]}",
            "",
            "def execute(request):",
            "    \"\"\"Generated by NeuroOps CodeWriterAgent.\"\"\"",
            "    result = process(request)",
            "    return result",
            "",
            "def process(data):",
            "    return {'status': 'ok', 'data': data}",
            "```",
        ]
        self.log("Generated implementation skeleton.")
        confidence = 0.82 if len(spec) > 20 else 0.6
        return "\n".join(lines), confidence


class DebuggerAgent(BaseAgent):
    department = "engineering"
    description = "Analyzes code for bugs and proposes fixes."

    def think(self, task: Task) -> tuple[str, float]:
        self.log("Scanning for common bug patterns...")
        code = task.description or ""
        issues = []
        if "except:" in code or "except Exception:" in code:
            issues.append("Broad exception catch detected — narrow the handler.")
        if re.search(r"\bprint\(", code):
            issues.append("Print statements found — use logging.")
        if "eval(" in code:
            issues.append("Use of eval() is unsafe.")
        if not issues:
            issues.append("No obvious bugs detected. Code looks clean.")
        self.log(f"Found {len(issues)} issue(s).")
        report = "## Debug Report\n\n" + "\n".join(f"- {i}" for i in issues)
        return report, 0.88 if issues else 0.7


class ReviewerAgent(BaseAgent):
    department = "engineering"
    description = "Reviews code for quality, style, and correctness."

    def think(self, task: Task) -> tuple[str, float]:
        self.log("Performing code review...")
        code = task.description or ""
        comments = []
        if len(code) < 50:
            comments.append("Implementation is very short — verify completeness.")
        if "TODO" in code or "FIXME" in code:
            comments.append("Unresolved TODO/FIXME markers present.")
        comments.append("Naming conventions appear consistent.")
        comments.append("Suggest adding unit tests for edge cases.")
        self.log("Review complete.")
        report = "## Code Review\n\n" + "\n".join(f"- {c}" for c in comments)
        return report, 0.85


class DocumentationAgent(BaseAgent):
    department = "engineering"
    description = "Generates documentation from code or specs."

    def think(self, task: Task) -> tuple[str, float]:
        self.log("Drafting documentation...")
        subject = task.title
        doc = [
            f"# Documentation: {subject}",
            "",
            "## Overview",
            f"{task.description or 'No description provided.'}",
            "",
            "## Usage",
            "```python",
            f"from module import {subject.lower().replace(' ', '_')}",
            "result = execute()",
            "```",
            "",
            "## Parameters",
            "- None documented yet.",
        ]
        self.log("Documentation generated.")
        return "\n".join(doc), 0.8
